#!/usr/bin/env python3
# Shared by build-opencode.sh's global and --project passes: inline every standalone `@path`
# import into one file, because opencode does NOT expand @imports. Fence-aware, cycle-safe, and
# rewrites $HOME to ~ so output is machine-portable. ONE copy so the passes cannot drift.
# Usage: python3 .opencode-flatten.py <root.md>   (prints to stdout)
import os, re, sys

HOME = os.path.expanduser("~")
IMPORT = re.compile(r'^\s*@(\S+)\s*$')   # whole line is just @path

def norm(s):
    """Replace the real home path with ~ so the output is machine-portable."""
    return s.replace(HOME, "~")

def expand(path, seen, depth=0):
    rp = os.path.realpath(os.path.expanduser(path))
    if rp in seen:
        return [f"<!-- skipped circular @import: {norm(path)} -->\n"]
    if not os.path.isfile(rp):
        return [f"<!-- missing @import: {norm(path)} -->\n"]
    seen = seen | {rp}
    out, in_fence = [], False
    with open(rp, encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if s.startswith("```"):
                in_fence = not in_fence
                out.append(norm(line)); continue
            m = None if in_fence else IMPORT.match(line)
            if m:
                imp = m.group(1)
                base = imp if imp.startswith(("/", "~")) else os.path.join(os.path.dirname(rp), imp)
                out.append(f"\n<!-- ↓ inlined from {norm(imp)} -->\n")
                out.extend(expand(base, seen, depth+1))
                out.append(f"<!-- ↑ end {norm(imp)} -->\n")
            else:
                out.append(norm(line))
    return out

root = sys.argv[1]
sys.stdout.write("<!-- GENERATED by build-opencode.sh — edit the Claude Code sources, not this file. -->\n\n")
sys.stdout.write("".join(expand(root, set())))
