#!/usr/bin/env bash
# build-opencode.sh — generate opencode artifacts from the canonical Claude Code config.
#
# Single source of truth = this repo (~/claude-config). This script emits the opencode
# equivalents into ./opencode/ so the two engines never drift:
#   1. AGENTS.md     — CLAUDE.md with every @import flattened in (opencode does NOT expand @imports)
#   2. opencode.json — permissions + model + MCP servers mapped from settings.json / ~/.claude.json
#   3. agent/*.md    — Claude subagent defs with `mode: subagent` injected
#
# Skills already work: opencode reads ~/.claude/skills/ directly, so they are NOT regenerated here.
#
# Usage:
#   ./build-opencode.sh                 # generate into ./opencode/
#   ./build-opencode.sh --install       # also symlink into ~/.config/opencode/
#   ./build-opencode.sh <src-CLAUDE.md> # override the root rules file
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_ROOT="${1:-$HOME/.claude/CLAUDE.md}"
[[ "$SRC_ROOT" == --* ]] && SRC_ROOT="$HOME/.claude/CLAUDE.md"   # first arg was a flag
INSTALL=0; for a in "$@"; do [[ "$a" == "--install" ]] && INSTALL=1; done

OUT="$REPO/opencode"
SETTINGS="$HOME/.claude/settings.json"
CLAUDE_JSON="$HOME/.claude.json"
AGENTS_SRC_DIR="$REPO/config/agents"

mkdir -p "$OUT/agent"
echo "▸ source rules : $SRC_ROOT"
echo "▸ output dir   : $OUT"

# ── 1. Flatten @imports → AGENTS.md ────────────────────────────────────────────
# Recursively inline standalone `@path` lines (abs, ~, or relative-to-importer).
# Skips imports inside ``` fenced code blocks and commented (`# @...`) lines.
python3 - "$SRC_ROOT" > "$OUT/AGENTS.md" <<'PY'
import os, re, sys

IMPORT = re.compile(r'^\s*@(\S+)\s*$')   # whole line is just @path

def expand(path, seen, depth=0):
    rp = os.path.realpath(os.path.expanduser(path))
    if rp in seen:
        return [f"<!-- skipped circular @import: {path} -->\n"]
    if not os.path.isfile(rp):
        return [f"<!-- missing @import: {path} -->\n"]
    seen = seen | {rp}
    out, in_fence = [], False
    with open(rp, encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if s.startswith("```"):
                in_fence = not in_fence
                out.append(line); continue
            m = None if in_fence else IMPORT.match(line)
            if m:
                imp = m.group(1)
                base = imp if imp.startswith(("/", "~")) else os.path.join(os.path.dirname(rp), imp)
                out.append(f"\n<!-- ↓ inlined from {imp} -->\n")
                out.extend(expand(base, seen, depth+1))
                out.append(f"<!-- ↑ end {imp} -->\n")
            else:
                out.append(line)
    return out

root = sys.argv[1]
sys.stdout.write("<!-- GENERATED by build-opencode.sh — edit the Claude Code sources, not this file. -->\n\n")
sys.stdout.write("".join(expand(root, set())))
PY
echo "✓ AGENTS.md      ($(wc -l < "$OUT/AGENTS.md" | tr -d ' ') lines)"

# ── 2. settings.json + mcpServers → opencode.json ──────────────────────────────
python3 - "$SETTINGS" "$CLAUDE_JSON" > "$OUT/opencode.json" <<'PY'
import json, sys

settings = json.load(open(sys.argv[1])) if __import__("os").path.isfile(sys.argv[1]) else {}
claude   = json.load(open(sys.argv[2])) if __import__("os").path.isfile(sys.argv[2]) else {}

cfg = {"$schema": "https://opencode.ai/config.json"}

# model: claude-sonnet-4-6 -> anthropic/claude-sonnet-4-6  (verify against your opencode provider)
m = settings.get("model")
if m:
    cfg["model"] = m if "/" in m else f"anthropic/{m}"

# permissions: allow-list -> opencode permission map (default everything else to "ask")
allow = settings.get("permissions", {}).get("allow", [])
bash = {"*": "ask"}
perm = {}
for entry in allow:
    if entry.startswith("Bash(") and entry.endswith(")"):
        bash[entry[5:-1]] = "allow"
    elif entry in ("Edit", "Write", "MultiEdit", "NotebookEdit"):
        perm["edit"] = "allow"
    elif entry == "Read":
        pass                       # always allowed in opencode
    elif entry.startswith("mcp__"):
        perm[entry[5:] + "*"] = "allow"   # mcp__playwright -> playwright*
if len(bash) > 1:
    perm["bash"] = bash
if perm:
    cfg["permission"] = perm

# MCP servers: Claude shape -> opencode shape (local=command array, remote=url)
mcp = {}
for name, s in (claude.get("mcpServers") or {}).items():
    if s.get("url") or s.get("type") in ("http", "sse", "remote"):
        e = {"type": "remote", "url": s.get("url"), "enabled": True}
        if s.get("headers") or s.get("env"):
            e["headers"] = s.get("headers") or s.get("env")
    else:
        cmd = [s.get("command")] + list(s.get("args", [])) if s.get("command") else []
        e = {"type": "local", "command": cmd, "enabled": True}
        if s.get("env"):
            e["environment"] = s["env"]
    mcp[name] = e
if mcp:
    cfg["mcp"] = mcp

print(json.dumps(cfg, indent=2))
PY
echo "✓ opencode.json"

# ── 3. agents → opencode agent/*.md (inject `mode: subagent`) ───────────────────
n=0
if [[ -d "$AGENTS_SRC_DIR" ]]; then
  for f in "$AGENTS_SRC_DIR"/*.md; do
    [[ -e "$f" ]] || continue
    python3 - "$f" "$OUT/agent/$(basename "$f")" <<'PY'
import re, sys
src, dst = sys.argv[1], sys.argv[2]
lines = open(src, encoding="utf-8").read().splitlines(keepends=True)

# Map Claude Code named colors -> OpenCode valid values (semantic or hex)
COLOR_MAP = {
    "yellow": "warning", "orange": "warning",
    "blue": "info",   "cyan": "info",
    "green": "success",
    "red": "error",   "pink": "error",
    "purple": "accent", "violet": "accent",
}

def transform_fm_line(line):
    # Drop tools: entirely — OpenCode schema expects object|undefined, not a CSV string
    if re.match(r'^\s*tools\s*:', line):
        return None
    # Map color: <name> -> OpenCode valid semantic color
    m = re.match(r'^(\s*color\s*:\s*)(\S+)\s*$', line)
    if m:
        val = m.group(2).strip('"\'')
        mapped = COLOR_MAP.get(val.lower())
        if mapped:
            return f"{m.group(1)}{mapped}\n"
    return line

if lines and lines[0].strip() == "---":
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end:
        fm_lines = lines[1:end]
        new_fm = [transform_fm_line(l) for l in fm_lines]
        new_fm = [l for l in new_fm if l is not None]
        if not any(l.strip().startswith("mode:") for l in new_fm):
            new_fm.insert(0, "mode: subagent\n")
        lines = ["---\n"] + new_fm + lines[end:]
    else:
        if not any(l.strip().startswith("mode:") for l in lines[1:]):
            lines.insert(1, "mode: subagent\n")
else:
    lines = ["---\nmode: subagent\n---\n"] + lines
open(dst, "w", encoding="utf-8").write("".join(lines))
PY
    n=$((n+1))
  done
fi
echo "✓ agent/         ($n files)"

# ── 4. skills → opencode/commands/*.md ─────────────────────────────────────────
SKILLS_SRC_DIR="$REPO/config/skills"
python3 - "$SKILLS_SRC_DIR" "$OUT/commands" <<'PY'
import os, re, sys

skills_dir, out_dir = sys.argv[1], sys.argv[2]
os.makedirs(out_dir, exist_ok=True)

FM_DELIM = re.compile(r'^---\s*$')

def parse_skill(path):
    lines = open(path, encoding='utf-8').read().splitlines(keepends=True)
    name = desc = None
    body_start = 0
    if lines and FM_DELIM.match(lines[0]):
        end = next((i for i in range(1, len(lines)) if FM_DELIM.match(lines[i])), None)
        if end:
            fm = ''.join(lines[1:end])
            m = re.search(r'^name:\s*(.+)$', fm, re.MULTILINE)
            if m: name = m.group(1).strip().strip('"\'')
            m = re.search(r'^description:\s*(.+)$', fm, re.MULTILINE)
            if m: desc = m.group(1).strip().strip('"\'')
            body_start = end + 1
    body = ''.join(lines[body_start:]).strip()
    return name, desc, body

n = 0
for entry in sorted(os.listdir(skills_dir)):
    entry_path = os.path.join(skills_dir, entry)
    if os.path.isdir(entry_path):
        skill_file = os.path.join(entry_path, 'SKILL.md')
        if not os.path.isfile(skill_file): continue
        path, skill_name = skill_file, entry
    elif entry.endswith('.md'):
        path, skill_name = entry_path, entry[:-3]
    else:
        continue
    fm_name, desc, body = parse_skill(path)
    cmd_name = fm_name or skill_name
    header = '---\n'
    if desc:
        safe_desc = desc.replace('"', '\\"')
        header += f'description: "{safe_desc}"\n'
    header += '---\n\n'
    with open(os.path.join(out_dir, f'{cmd_name}.md'), 'w', encoding='utf-8') as f:
        f.write(header + body + '\n')
    n += 1
PY
echo "✓ commands/      ($(ls "$OUT/commands" | wc -l | tr -d ' ') files)"

# ── 5. optional install: symlink into ~/.config/opencode/ ──────────────────────
if [[ "$INSTALL" == "1" ]]; then
  DEST="$HOME/.config/opencode"
  mkdir -p "$DEST/plugins"
  ln -sfn "$OUT/AGENTS.md"                 "$DEST/AGENTS.md"
  ln -sfn "$OUT/opencode.json"             "$DEST/opencode.json"
  ln -sfn "$OUT/agent"                     "$DEST/agent"
  ln -sfn "$OUT/commands"                  "$DEST/commands"
  ln -sfn "$OUT/plugins/safety-hooks.ts"   "$DEST/plugins/safety-hooks.ts"
  echo "✓ installed → $DEST (symlinks)"
fi

# ── manual follow-ups the generator deliberately does NOT do ───────────────────
cat <<'EOF'

── done. Still needs a human (out of scope for static generation): ──
  • Hooks: safety-hooks.ts is symlinked into ~/.config/opencode/plugins/ (when --install
    is used). It covers dangerous-cmd, force-push, secrets, and pre-push quality gates.
    No "opencode plugin add" command exists — plugins are files in the plugins/ directory.
  • Orchestration skills (/build, /rplan→/approved→/qa→/reviewer): they run as
    markdown but the Agent/Skill multi-agent control flow is Claude-runtime-specific.
    Re-express in opencode's agent system before relying on /build.
  • Verify the model id ("model" in opencode.json) against your opencode provider/auth
    (Anthropic API key vs Claude Pro/Max bridge plugin).
  • Commit ./opencode/ so both engines stay versioned from one source.
EOF
