#!/usr/bin/env bash
# build-opencode.sh — generate opencode artifacts from the canonical Claude Code config.
#
# Single source of truth = this repo (~/claude-config). This script emits the opencode
# equivalents into ./opencode/ so the two engines never drift:
#   1. AGENTS.md     — CLAUDE.md with every @import flattened in (opencode does NOT expand @imports)
#   2. opencode.json — permissions + model + MCP servers mapped from settings.json / ~/.claude.json
#   3. agent/*.md    — Claude subagent defs with `mode: subagent` injected
#
# Skills already work: opencode reads ~/.claude/skills/ directly, so they are NOT regenerated here.
#
# Usage:
#   ./build-opencode.sh                 # generate into ./opencode/
#   ./build-opencode.sh --install       # also symlink into ~/.config/opencode/
#   ./build-opencode.sh <src-CLAUDE.md> # override the root rules file
#
# PROJECT MODE — the global pass above covers ~/.claude only, so a repo's OWN config is invisible
# to opencode: its CLAUDE.md, its .claude/agents/, its .claude/skills/. That silently downgrades
# any skill written to prefer a project override (e.g. /reviewer looks for
# .claude/agents/reviewer.md and falls back to a generic checklist when it is absent).
#
#   ./build-opencode.sh --project <repo>   # emit <repo>/AGENTS.md + <repo>/.opencode/{agent,command}
#
# Output paths were verified against opencode 1.18.16 by probe, not assumed:
#   <repo>/AGENTS.md            — opencode's instruction file (it does NOT read CLAUDE.md)
#   <repo>/.opencode/agent/     — project subagents  (probe: `opencode agent list` saw it)
#   <repo>/.opencode/command/   — project commands   (probe: `opencode run --command` resolved it)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL=0; FROM_PLUGIN=0; PROJECT=""
prev=""
for a in "$@"; do
  [[ "$a" == "--install" ]] && INSTALL=1
  [[ "$a" == "--from-plugin" ]] && FROM_PLUGIN=1
  [[ "$prev" == "--project" ]] && PROJECT="$a"
  [[ "$a" == --project=* ]] && PROJECT="${a#--project=}"
  prev="$a"
done

# ── PROJECT MODE ───────────────────────────────────────────────────────────────
# Mirrors a REPO's own Claude config into the layout opencode reads, then exits. Deliberately
# separate from the global pass: different sources, different destination, and it must never touch
# ~/.config/opencode (a project's rules are not global rules).
if [[ -n "$PROJECT" ]]; then
  PROJ="$(cd "$PROJECT" 2>/dev/null && pwd)" || { echo "✗ no such directory: $PROJECT" >&2; exit 1; }
  SRC_CLAUDE="$PROJ/CLAUDE.md"
  echo "▸ project      : $PROJ"

  # 1. CLAUDE.md → AGENTS.md, @imports flattened. opencode reads AGENTS.md and does NOT expand
  #    @imports, so an unflattened copy would silently drop every imported rule file.
  if [[ -f "$SRC_CLAUDE" ]]; then
    { echo "<!-- GENERATED by build-opencode.sh --project — edit CLAUDE.md, not this file. -->"
      python3 "$REPO/.opencode-flatten.py" "$SRC_CLAUDE"
    } > "$PROJ/AGENTS.md"
    echo "✓ AGENTS.md      ($(wc -l < "$PROJ/AGENTS.md" | tr -d ' ') lines, @imports inlined)"
  else
    echo "⏭ AGENTS.md      (no CLAUDE.md in $PROJ)"
  fi

  # 2. .claude/agents/*.md → .opencode/agent/*.md, with `mode: subagent` injected.
  mkdir -p "$PROJ/.opencode/agent"
  n=0
  if [[ -d "$PROJ/.claude/agents" ]]; then
    for f in "$PROJ/.claude/agents"/*.md; do
      [[ -e "$f" ]] || continue
      OPENCODE_AGENT_SRC="$f" OPENCODE_AGENT_DST="$PROJ/.opencode/agent/$(basename "$f")" \
        python3 "$REPO/.opencode-agent-transform.py" 2>/dev/null || cp "$f" "$PROJ/.opencode/agent/$(basename "$f")"
      n=$((n+1))
    done
  fi
  echo "✓ .opencode/agent/    ($n files)"

  # 3. .claude/skills/<name>/SKILL.md → .opencode/command/<name>.md. opencode's project commands are
  #    flat files, so the skill's directory name becomes the command name.
  mkdir -p "$PROJ/.opencode/command"
  s=0
  if [[ -d "$PROJ/.claude/skills" ]]; then
    for d in "$PROJ/.claude/skills"/*/; do
      [[ -f "$d/SKILL.md" ]] || continue
      cp "$d/SKILL.md" "$PROJ/.opencode/command/$(basename "${d%/}").md"
      s=$((s+1))
    done
  fi
  echo "✓ .opencode/command/  ($s files)"

  cat <<EOF

── project config mirrored. Commit AGENTS.md and .opencode/ so both engines stay versioned. ──
  Re-run after changing CLAUDE.md, .claude/agents/ or .claude/skills/ — this is a generator,
  not a live view. Verify with:  cd "$PROJ" && opencode agent list
EOF
  exit 0
fi

# --from-plugin: generate from what the PLUGIN ships, not from the owner's personal ~/.claude.
# Without it, AGENTS.md carries whoever ran the script (their machine paths, their personal @imports,
# their permission allowlist) — fine for the owner, useless as something to distribute. With it the
# output is portable: instructions/core.md is the source of rules, and personal settings are ignored.
if [[ "$FROM_PLUGIN" == "1" ]]; then
  SRC_ROOT="${SAKI_PLUGIN_ROOT:-$REPO}/instructions/core.md"
  SETTINGS="/dev/null"
  CLAUDE_JSON="/dev/null"
  OUT="${OPENCODE_OUT:-$REPO/opencode}"
else
  SRC_ROOT="${1:-$HOME/.claude/CLAUDE.md}"
  [[ "$SRC_ROOT" == --* ]] && SRC_ROOT="$HOME/.claude/CLAUDE.md"   # first arg was a flag
  SETTINGS="$HOME/.claude/settings.json"
  CLAUDE_JSON="$HOME/.claude.json"
  OUT="${OPENCODE_OUT:-$REPO/opencode}"
fi
AGENTS_SRC_DIR="$REPO/config/agents"

mkdir -p "$OUT/agent"
echo "▸ source rules : $SRC_ROOT$([[ "$FROM_PLUGIN" == "1" ]] && echo '  (plugin defaults)')"
echo "▸ output dir   : $OUT"

# ── 1. Flatten @imports → AGENTS.md ────────────────────────────────────────────
# Recursively inline standalone `@path` lines (abs, ~, or relative-to-importer).
# Skips imports inside ``` fenced code blocks and commented (`# @...`) lines.
python3 "$REPO/.opencode-flatten.py" "$SRC_ROOT" > "$OUT/AGENTS.md"
# Agent mode is opt-in here too: opencode has no per-session env gate on an instructions file, so the
# overlay is baked in only when the bridge is built FOR a runner. An interactive opencode install
# never sees it.
if [[ "$FROM_PLUGIN" == "1" && "${SAKI_AGENT_MODE:-}" == "1" ]]; then
  AGENT_MODE_MD="${SAKI_PLUGIN_ROOT:-$REPO}/instructions/agent-mode.md"
  if [[ -f "$AGENT_MODE_MD" ]]; then
    printf '\n<!-- ↓ agent mode (autonomous runner) -->\n' >> "$OUT/AGENTS.md"
    cat "$AGENT_MODE_MD" >> "$OUT/AGENTS.md"
    echo "✓ agent-mode overlay appended (SAKI_AGENT_MODE=1)"
  fi
fi
echo "✓ AGENTS.md      ($(wc -l < "$OUT/AGENTS.md" | tr -d ' ') lines)"

# ── 2. settings.json + mcpServers → opencode.json ──────────────────────────────
python3 - "$SETTINGS" "$CLAUDE_JSON" > "$OUT/opencode.json" <<'PY'
import json, sys

settings = json.load(open(sys.argv[1])) if __import__("os").path.isfile(sys.argv[1]) else {}
claude   = json.load(open(sys.argv[2])) if __import__("os").path.isfile(sys.argv[2]) else {}

cfg = {"$schema": "https://opencode.ai/config.json"}

# Only preserve an explicitly provider-qualified model. A Claude alias or bare model id has no
# portable meaning in OpenCode and must be resolved by the OpenCode host/runner instead.
m = settings.get("model")
if m and "/" in m:
    cfg["model"] = m

# permissions: allow-list -> opencode permission map (default everything else to "ask")
allow = settings.get("permissions", {}).get("allow", [])
bash = {"*": "ask"}
perm = {}
# Only these inspection commands are safe to auto-allow. Everything else, including test/build/
# runtime families and mutating or network commands, remains behind the catch-all approval gate.
safe_bash_patterns = {
    "ls",
    "ls *",
    "cat *",
    "echo *",
    "cd *",
    "grep *",
    "tail *",
    "head *",
    "wc *",
    "which *",
    "sort *",
    "uniq *",
    "column *",
    "git status",
    "git status --short",
    "git diff",
    "git diff --check",
    "git diff --stat",
    "git diff --name-only",
    "git log",
    "git log --oneline",
}
for entry in allow:
    if entry.startswith("Bash(") and entry.endswith(")"):
        pattern = entry[5:-1]
        if pattern in safe_bash_patterns:
            bash[pattern] = "allow"
    elif entry in ("Edit", "Write", "MultiEdit", "NotebookEdit"):
        perm["edit"] = "allow"
    elif entry == "Read":
        pass                       # always allowed in opencode
    elif entry.startswith("mcp__"):
        perm[entry[5:] + "*"] = "allow"   # mcp__playwright -> playwright*
if len(bash) > 1:
    perm["bash"] = bash

# --from-plugin has no personal allowlist to map, and an empty `permission` block means opencode
# asks for everything — unusable for a runner. Ship the plugin's own posture instead: reads and
# edits flow, every bash command is gated, and the real guard stays the safety hooks (which run
# regardless of this setting), exactly as on the Claude side.
if not perm:
    perm = {"edit": "allow", "bash": {"*": "ask"}}
cfg["permission"] = perm

# MCP servers: Claude shape -> opencode shape (local=command array, remote=url)
mcp = {}
for name, s in (claude.get("mcpServers") or {}).items():
    if s.get("url") or s.get("type") in ("http", "sse", "remote"):
        e = {"type": "remote", "url": s.get("url"), "enabled": True}
        if s.get("headers") or s.get("env"):
            e["headers"] = s.get("headers") or s.get("env")
    else:
        cmd = [s.get("command")] + list(s.get("args", [])) if s.get("command") else []
        e = {"type": "local", "command": cmd, "enabled": True}
        if s.get("env"):
            e["environment"] = s["env"]
    mcp[name] = e
if mcp:
    cfg["mcp"] = mcp

print(json.dumps(cfg, indent=2))
PY
echo "✓ opencode.json"

# ── 3. agents → opencode agent/*.md (inject `mode: subagent`) ───────────────────
n=0
if [[ -d "$AGENTS_SRC_DIR" ]]; then
  for f in "$AGENTS_SRC_DIR"/*.md; do
    [[ -e "$f" ]] || continue
    OPENCODE_AGENT_SRC="$f" OPENCODE_AGENT_DST="$OUT/agent/$(basename "$f")" \
      python3 "$REPO/.opencode-agent-transform.py"
    n=$((n+1))
  done
fi
echo "✓ agent/         ($n files)"

# ── 4. skills → opencode/commands/*.md ─────────────────────────────────────────
SKILLS_SRC_DIR="$REPO/config/skills"
python3 - "$SKILLS_SRC_DIR" "$OUT/commands" <<'PY'
import os, re, sys

skills_dir, out_dir = sys.argv[1], sys.argv[2]
os.makedirs(out_dir, exist_ok=True)

FM_DELIM = re.compile(r'^---\s*$')

def parse_skill(path):
    lines = open(path, encoding='utf-8').read().splitlines(keepends=True)
    name = desc = None
    body_start = 0
    if lines and FM_DELIM.match(lines[0]):
        end = next((i for i in range(1, len(lines)) if FM_DELIM.match(lines[i])), None)
        if end:
            fm = ''.join(lines[1:end])
            m = re.search(r'^name:\s*(.+)$', fm, re.MULTILINE)
            if m: name = m.group(1).strip().strip('"\'')
            m = re.search(r'^description:\s*(.+)$', fm, re.MULTILINE)
            if m: desc = m.group(1).strip().strip('"\'')
            body_start = end + 1
    body = ''.join(lines[body_start:]).strip()
    return name, desc, body

n = 0
for entry in sorted(os.listdir(skills_dir)):
    entry_path = os.path.join(skills_dir, entry)
    if os.path.isdir(entry_path):
        skill_file = os.path.join(entry_path, 'SKILL.md')
        if not os.path.isfile(skill_file): continue
        path, skill_name = skill_file, entry
    elif entry.endswith('.md'):
        path, skill_name = entry_path, entry[:-3]
    else:
        continue
    fm_name, desc, body = parse_skill(path)
    cmd_name = fm_name or skill_name
    header = '---\n'
    if desc:
        safe_desc = desc.replace('"', '\\"')
        header += f'description: "{safe_desc}"\n'
    header += '---\n\n'
    with open(os.path.join(out_dir, f'{cmd_name}.md'), 'w', encoding='utf-8') as f:
        f.write(header + body + '\n')
    n += 1
PY
echo "✓ commands/      ($(ls "$OUT/commands" | wc -l | tr -d ' ') files)"

# OpenCode registers generated commands under bare names (/rplan, /qa, ...), while the canonical
# Claude sources use the /saki-builder:<name> namespace. Keep checked-in and generated artifacts
# executable in OpenCode, including AGENTS.md and subagent instructions that refer to commands.
for stage in "$OUT/commands" "$OUT/AGENTS.md" "$OUT/agent"; do
  node "$REPO/bin/namespace-refs.js" --reverse --dir "$stage" >/dev/null
done
echo "✓ refs          (de-namespaced for OpenCode)"

# ── 5. optional install: symlink into ~/.config/opencode/ ──────────────────────
if [[ "$INSTALL" == "1" ]]; then
  DEST="$HOME/.config/opencode"
  mkdir -p "$DEST/plugins"
  ln -sfn "$OUT/AGENTS.md"                 "$DEST/AGENTS.md"
  ln -sfn "$OUT/opencode.json"             "$DEST/opencode.json"
  ln -sfn "$OUT/agent"                     "$DEST/agent"
  ln -sfn "$OUT/commands"                  "$DEST/commands"
  ln -sfn "$OUT/plugins/safety-hooks.ts"   "$DEST/plugins/safety-hooks.ts"
  echo "✓ installed → $DEST (symlinks)"
fi

# ── manual follow-ups the generator deliberately does NOT do ───────────────────
cat <<'EOF'

── done. Still needs a human (out of scope for static generation): ──
  • Hooks: safety-hooks.ts is symlinked into ~/.config/opencode/plugins/ (when --install
    is used). It covers dangerous-cmd, force-push, secrets, and pre-push quality gates.
    No "opencode plugin add" command exists — plugins are files in the plugins/ directory.
  • Orchestration skills (/build, /rplan→/approved→/qa→/reviewer): they run as
    markdown but the Agent/Skill multi-agent control flow is Claude-runtime-specific.
    Re-express in opencode's agent system before relying on /build.
  • Resolve each skill's `model_requirement` through OpenCode's native model picker or runner.
    The generator only preserves an explicitly qualified `provider/model` value.
  • Commit ./opencode/ so both engines stay versioned from one source.
EOF
